import './globals.css'

import Link from 'next/link'

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by juniahn',
}

export default async function RootLayout({ children }) {
  const response = await fetch('http://localhost:9999/topics');
  const topics = await response.json();

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="Delete" /></li>
        </ul>
      </body>
    </html>
  )
}
